import React,{useEffect,useMemo,useState} from 'react';
import {Alert,FlatList,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {agroTheme as theme} from '../services/designTokens';
import {listEntity,removeEntity,upsertEntity} from '../services/localAgroService';

const CONFIG={
properties:{title:'Propriedades',icon:'business-outline',fields:[['nome','Nome'],['municipio','Município'],['estado','Estado'],['area','Área (ha)']]},
fields:{title:'Talhões',icon:'map-outline',fields:[['nome','Nome'],['codigo','Código'],['area','Área (ha)'],['cultura','Cultura']]},
crops:{title:'Culturas',icon:'leaf-outline',fields:[['nome','Nome'],['ciclo','Ciclo'],['observacoes','Observações']]},
seasons:{title:'Safras',icon:'calendar-outline',fields:[['nome','Safra'],['cultura','Cultura'],['area','Área (ha)'],['status','Status']]},
activities:{title:'Atividades',icon:'checkmark-circle-outline',fields:[['titulo','Título'],['responsavel','Responsável'],['prioridade','Prioridade'],['status','Status']]},
documents:{title:'Documentos',icon:'document-text-outline',fields:[['titulo','Título'],['categoria','Categoria'],['arquivo','Arquivo / URL']]},
reports:{title:'Relatórios',icon:'bar-chart-outline',fields:[['titulo','Título'],['periodo','Período'],['observacoes','Observações']]}
};

export default function AgroModuleScreen({route,navigation}){
const type=route?.params?.type||'properties';const config=CONFIG[type]||CONFIG.properties;
const[items,setItems]=useState([]);const[form,setForm]=useState({});const[search,setSearch]=useState('');const[editing,setEditing]=useState(null);
const refresh=async()=>setItems(await listEntity(type));useEffect(()=>{refresh()},[type]);
const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?items.filter(x=>Object.values(x).some(v=>String(v??'').toLowerCase().includes(q))):items},[items,search]);
const save=async()=>{const first=config.fields[0];if(!String(form[first[0]]||'').trim()){Alert.alert('Campo obrigatório','Informe '+first[1]+'.');return}await upsertEntity(type,{...form,...(editing?{id:editing}:{})});setForm({});setEditing(null);refresh()};
const edit=item=>{setEditing(item.id);setForm(item)};
const remove=item=>Alert.alert('Excluir registro','A operação ficará registrada para sincronização.',[{text:'Cancelar',style:'cancel'},{text:'Excluir',style:'destructive',onPress:async()=>{await removeEntity(type,item.id);refresh()}}]);
return <SafeAreaView style={s.safe}>
<View style={s.header}><Pressable onPress={()=>navigation.goBack()} style={s.back}><Ionicons name="arrow-back" size={22} color={theme.colors.text}/></Pressable><View style={{flex:1}}><Text style={s.title}>{config.title}</Text><Text style={s.subtitle}>Modo campo • offline-first</Text></View><View style={s.status}><View style={s.dot}/><Text style={s.statusText}>CAMPO</Text></View></View>
<FlatList data={filtered} keyExtractor={x=>x.id} contentContainerStyle={s.content} ListHeaderComponent={<><TextInput value={search} onChangeText={setSearch} placeholder="Buscar..." placeholderTextColor={theme.colors.textSecondary} style={s.search}/><View style={s.form}><Text style={s.formTitle}>{editing?'Editar registro':'Novo registro'}</Text>{config.fields.map(([k,l])=><TextInput key={k} value={String(form[k]??'')} onChangeText={v=>setForm(f=>({...f,[k]:v}))} placeholder={l} placeholderTextColor={theme.colors.textSecondary} style={s.input}/>)}<View style={s.actions}><Pressable onPress={save} style={s.primary}><Ionicons name="save-outline" size={18} color="#fff"/><Text style={s.primaryText}>{editing?'Atualizar':'Salvar'}</Text></Pressable>{editing&&<Pressable onPress={()=>{setEditing(null);setForm({})}} style={s.secondary}><Text>Cancelar</Text></Pressable>}</View></View><Text style={s.count}>{filtered.length} registro(s)</Text></>}
renderItem={({item})=><View style={s.item}><View style={s.itemIcon}><Ionicons name={config.icon} size={21} color={theme.colors.primary}/></View><View style={{flex:1}}><Text style={s.itemTitle}>{item[config.fields[0][0]]}</Text><Text style={s.meta}>{config.fields.slice(1).map(x=>item[x[0]]?x[1]+': '+item[x[0]]:'').filter(Boolean).join(' • ')||'Registro local'}</Text></View><Pressable onPress={()=>edit(item)} style={s.small}><Ionicons name="create-outline" size={18} color={theme.colors.primary}/></Pressable><Pressable onPress={()=>remove(item)} style={s.small}><Ionicons name="trash-outline" size={18} color={theme.colors.danger}/></Pressable></View>}
ListEmptyComponent={<View style={s.empty}><Ionicons name={config.icon} size={40} color={theme.colors.primary}/><Text style={s.emptyTitle}>Nenhum registro</Text><Text style={s.emptyText}>Cadastre dados mesmo sem internet. Eles ficam na fila de sincronização.</Text></View>}/>
</SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.colors.background},content:{padding:16,paddingBottom:40},header:{flexDirection:'row',alignItems:'center',padding:16,backgroundColor:'#fff',borderBottomWidth:1,borderBottomColor:theme.colors.border},back:{width:42,height:42,borderRadius:21,backgroundColor:theme.colors.surfaceSecondary,alignItems:'center',justifyContent:'center',marginRight:12},title:{fontSize:22,fontWeight:'800',color:theme.colors.text},subtitle:{fontSize:12,color:theme.colors.textSecondary,marginTop:2},status:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:theme.colors.primaryLight,paddingHorizontal:9,paddingVertical:7,borderRadius:20},dot:{width:7,height:7,borderRadius:4,backgroundColor:theme.colors.success},statusText:{fontSize:10,fontWeight:'800',color:theme.colors.primary},search:{height:46,borderWidth:1,borderColor:theme.colors.border,borderRadius:12,backgroundColor:'#fff',paddingHorizontal:14,color:theme.colors.text,marginBottom:12},form:{backgroundColor:'#fff',borderRadius:16,padding:14,borderWidth:1,borderColor:theme.colors.border,marginBottom:16},formTitle:{fontSize:15,fontWeight:'800',color:theme.colors.text,marginBottom:10},input:{minHeight:44,borderWidth:1,borderColor:theme.colors.border,borderRadius:10,paddingHorizontal:12,color:theme.colors.text,backgroundColor:theme.colors.background,marginBottom:10},actions:{flexDirection:'row',gap:8},primary:{flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center',backgroundColor:theme.colors.primary,borderRadius:10,paddingHorizontal:16,paddingVertical:11},primaryText:{color:'#fff',fontWeight:'800'},secondary:{justifyContent:'center',paddingHorizontal:16,borderRadius:10,backgroundColor:theme.colors.surfaceSecondary},count:{fontSize:12,fontWeight:'700',color:theme.colors.textSecondary,marginBottom:8},item:{flexDirection:'row',alignItems:'center',backgroundColor:'#fff',borderWidth:1,borderColor:theme.colors.border,borderRadius:14,padding:12,marginBottom:8},itemIcon:{width:40,height:40,borderRadius:12,backgroundColor:theme.colors.primaryLight,alignItems:'center',justifyContent:'center',marginRight:10},itemTitle:{fontSize:15,fontWeight:'800',color:theme.colors.text},meta:{fontSize:12,color:theme.colors.textSecondary,marginTop:4},small:{width:36,height:36,alignItems:'center',justifyContent:'center'},empty:{alignItems:'center',padding:35},emptyTitle:{fontSize:16,fontWeight:'800',color:theme.colors.text,marginTop:10},emptyText:{fontSize:13,color:theme.colors.textSecondary,textAlign:'center',marginTop:6,maxWidth:420}});
